server:
  port: 9000
spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/eagle_eye_local
    driver-class-name: org.postgresql.Driver
    tomcat:
      validation-query: "SELECT 1"
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
